### ISSUE TITLE
Sending streaming audio

### ISSUE THREAD

**Issue by ryan-netizen** [watson-developer-cloud/go-sdk#108]
Hi, 

I could not find an option letting the user to send the streaming audio using the golang sdk, though the same option is available in python sdk version. 

I see at the moment it let you send the audio in one go. It would be better if we can have a function taking the audio channel of streaming audio and sends the stop message upon channel closure. Or through a different option.

Ryan

**Comment by repjarms** [comment]
Closing as a duplicate of #109
