### ISSUE TITLE
[speech-to-text] SpeechRecognitionResult.WordConfidence Unmarshal Error

### ISSUE THREAD

**Issue by theThinkingCap** [watson-developer-cloud/go-sdk#12]
### Dependencies 
- Gorilla Websockets
- encoding/json

### Steps
- Connect to STT with Gorillas websocket connection, **RecognizeOptions.WordConfidence** = true, **model** = ja-JP_NarrowbandModel
- Wait for message via websocketConnection.ReadMessage()
- Unmarshal message to _speechtotextv1.SpeechRecognitionResults_

### Expected Behaviour
- Everything unmarshals nicely and no error

### Actual Behaviour
- **Error**: json: cannot unmarshal array into Go struct field _SpeechRecognitionAlternative.word_confidence_ of type string
- If **RecognizeOptions.WordConfidence** set to false, everything unmarshals correctly

### Go SDK version
v0.2.0

### Possible Cause
Watson returns _SpeechRecognitionAlternative.word_confidence_ as an array of ["string", int].

Should _SpeechRecognitionAlternative.word_confidence_ type be changed to accommodate this?

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by theThinkingCap** [comment]
Sure, I'd be glad to! What's the standard procedure that I would need to follow?

**Comment by ehdsouza** [comment]
@theThinkingCap this SDK doesn't yet support the web socket implementation for recognize. 

In python for example, here is the method `recognize_using_websocket` https://github.com/watson-developer-cloud/python-sdk/blob/master/watson_developer_cloud/speech_to_text_v1_adapter.py#L29

So, I guess you are writing the underlying implementation using `Gorilla Websockets`. You could look into curl example.

**Comment by germanattanasio** [comment]
@ehdsouza I thought we supported websockets 🤔 so we released an sdk without websockets?

@theThinkingCap The process is partially documented in the [CONTRIBUTING.md](https://github.com/watson-developer-cloud/go-sdk/blob/master/.github/CONTRIBUTING.md) file.

First, you need to write an issue describing what you are going to do. In this case, you want to add WebSockets support and your idea is to use the Gorilla library.
Once you have that issue, there will be some discussion around the dependency and the interface we want to provide. Once that's settled you will write the code, and some tests in a Pull Request and we will merge it and acknowledge you in the README.

Does this sound like that plan? :nerd_face:

**Comment by theThinkingCap** [comment]
Sounds good! I was thinking of wrapping the standard websocket read/write operations, and then unmarshalling the STT result into a custom struct. This struct would probably have _SpeechRecognitionAlternative.word_confidence_ as type interface{}, so the unmarshalling problem should be solved. 
Is there anything else that I should keep in mind?

**Comment by ehdsouza** [comment]
@theThinkingCap, we would essentially need a method like this,
```go
func (speechToText *SpeechToTextV1) RecognizeUsingWebsocket(recognizeOptions *RecognizeOptions) (*core.DetailedResponse, error) {
```

This method would have to carry out the two types of authentications, (either basic auth or IAM), would internally use the `Gorilla` web socket library to stream the speech, and receive the contents. I haven't explored the `Gorilla` library as yet, but I can give you a gist of how we do it in python SDK.
Do have a look at the documentation: https://cloud.ibm.com/apidocs/speech-to-text#websocket_methods

In python, this is the https://github.com/watson-developer-cloud/python-sdk/blob/master/watson_developer_cloud/speech_to_text_v1_adapter.py#L29 method which internally uses the websocket library. It has a callback which is called upon events like `on_close`, `on_data`, `on_error`, etc.

Also, why do you feel Watson returns SpeechRecognitionAlternative.word_confidence as an array of ["string", int]? I just checked the swagger specifications, and it is suppose to be an array of strings:
```json
    "SpeechRecognitionAlternative": {
      "required": [
        "transcript"
      ],
      "properties": {
        "transcript": {
          "description": "A transcription of the audio.",
          "type": "string"
        },
        "confidence": {
          "description": "A score that indicates the service's confidence in the transcript in the range of 0.0 to 1.0. A confidence score is returned only for the best alternative and only with results marked as final.",
          "type": "number",
          "format": "double",
          "minimum": 0,
          "maximum": 1
        },
        "timestamps": {
          "description": "Time alignments for each word from the transcript as a list of lists. Each inner list consists of three elements: the word followed by its start and end time in seconds, for example: `[[\"hello\",0.0,1.2],[\"world\",1.2,2.5]]`. Timestamps are returned only for the best alternative.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "word_confidence": {
          "description": "A confidence score for each word of the transcript as a list of lists. Each inner list consists of two elements: the word and its confidence score in the range of 0.0 to 1.0, for example: `[[\"hello\",0.95],[\"world\",0.866]]`. Confidence scores are returned only for the best alternative and only with results marked as final.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
```

**Comment by theThinkingCap** [comment]
@ehdsouza I did a couple of tests, and unfortunately, it seems that Watson returns only ["string", int] for _SpeechRecognitionAlternative.word_confidence_. 
Please see the attached images. (One of them details the error message that I raised in my 1st comment)
<img width="858" alt="screen shot 2018-12-21 at 16 36 15" src="https://user-images.githubusercontent.com/17632500/50333943-24862280-054a-11e9-87a9-ace25133f6db.png">
<img width="858" alt="screen shot 2018-12-21 at 17 55 23" src="https://user-images.githubusercontent.com/17632500/50333970-35369880-054a-11e9-87b5-a0487078c485.png">
Therefore, I'd like to propose a change to the _SpeechRecognitionAlternative.word_confidence_ type. Would that be okay?

**Comment by ehdsouza** [comment]
@theThinkingCap I crossed checked with the doc writers and there seems to be a problem with the swagger. 😞 

Since you have pointed it out, do you want to create a separate PR correcting https://github.com/watson-developer-cloud/go-sdk/blob/master/speechtotextv1/speech_to_text_v1.go#L4709 and https://github.com/watson-developer-cloud/go-sdk/blob/master/speechtotextv1/speech_to_text_v1.go#L4714 to be of type `interface{}` so that even `Recognize` would work.

**Comment by theThinkingCap** [comment]
Sure. I'll fix up wordConfidence and timestamps with this issue, and open a new issue for websocket support.
