### ISSUE TITLE
[speech-to-text] Websocket support for Recognize

### ISSUE THREAD

**Issue by theThinkingCap** [watson-developer-cloud/go-sdk#14]
See #12 for discussion on Websocket support

**Possible Solution:** Open a Gorilla websocket connection with STT WS url, and perform read/write operations

**Comment by theThinkingCap** [comment]
@ehdsouza I took a look into the Python implementation of RecognizeWithWS, and it appears that it implements a listener. Could you help clarify if the following interpretations are correct?
**1)** Audio (the one sent to RecognizeWithWS) is an IO stream
**2)** Each call to RecognizeWithWS creates a new WS connection
**3)** RecognizeWithWS recognizes audio asynchronously

**Comment by ehdsouza** [comment]
@theThinkingCap The method is `recognize_using_websocket`, yes the interpretation is right. Ill add additionally that if you read the documentation: https://cloud.ibm.com/apidocs/speech-to-text#recognize-audio-websockets-, we need to send the start and stop messages.
