### ISSUE TITLE
Ability to stop/start audio recognition on websocket.

### ISSUE THREAD

**Issue by zkanda** [watson-developer-cloud/go-sdk#44]
Hello IBM Team,

Based on the [docs](https://cloud.ibm.com/docs/services/speech-to-text?topic=speech-to-text-websockets#WSstop), it seems to be intended that we can easily start/stop an audio recognition. However, the current implementation doesn't return the websocket `conn` or exposes the [start and stop function](https://github.com/watson-developer-cloud/go-sdk/blob/32ae41dc0825060f669e1fb9742fe95b34b4d6de/speechtotextv1/websocket_listener.go#L76-L89)

Maybe I just misunderstood but if there's a way to do it currently, I'd be glad to know.

Cheers

**Comment by ehdsouza** [comment]
Hi @zkanda,

The current implementation unfortunately doesn't expose those methods

Do you have a design in mind? You could start with a PR or comment here

**Comment by zkanda** [comment]
Hello @ehdsouza there are many ways to get it done, I'm not sure if there's an ibm way of doing things but here are some of my thoughts.

*  We can return the `conn` so we can manipulate those ourselves, but that can get quite verbose. We would need to find a way to synchronize it with other goroutines, e.g. we need to be able to say stop sending audio before sending the `stop` command. hmmm I think this might get ugly on the client side.
* Maybe a better is to return `RecognizeListener`? Then attach and expose those methods of start/stop? That way, the library can handle the complexity of synchronizing those goroutines.

If you have some other ideas, I would be glad to know. I can try doing the implementation.

**Comment by ehdsouza** [comment]
Approach 2 sounds a better way to get started. 

Also feel free to write in an example in the folder here: https://github.com/watson-developer-cloud/go-sdk/tree/master/examples. In some of our SDKs, we give an example where the input is from a microphone
