### ISSUE TITLE
The official API documentations don't reflect the changes in authentication methods

### ISSUE THREAD

**Issue by sanghunkang** [watson-developer-cloud/go-sdk#55]
As the title. While I was working with go-sdk for Watson Assistant, I found that the examples in the official documentation(https://cloud.ibm.com/apidocs/assistant-v1?code=go) not only doesn't work, but also does not reflect recent updates you made (https://github.com/watson-developer-cloud/go-sdk/commit/554c926)

To be specific, I failed to build a go program with the example given in the current documentation, but succeeded with your updated example at the commit I mentioned.

I further found that other services have the same problem as well. And I guess it is so for all Watson products.
- https://cloud.ibm.com/apidocs/speech-to-text?code=go
- https://cloud.ibm.com/apidocs/discovery?code=go

I think the documentations need to be synced.

**Comment by ehdsouza** [comment]
@sanghunkang, the docs are underway for our official release happening soon. For now the official docs would match a release <= https://github.com/watson-developer-cloud/go-sdk/releases/tag/v0.11.0.

Sorry for the delay.

**Comment by ehdsouza** [comment]
These are the versions in sync with the docs:
```
go get github.com/IBM/go-sdk-core@v0.4.2
go get github.com/watson-developer-cloud/go-sdk@v0.11.0
```

**Comment by ehdsouza** [comment]
The official API docs have been updated. Refer to [MIGRATION-V1](https://github.com/watson-developer-cloud/go-sdk/blob/v1.0.0/MIGRATION-V1.md) to move from `v0.11.0` to `v1.0.0`
