### ISSUE TITLE
Compare Comply ListFeedback does not work

### ISSUE THREAD

**Issue by dpopp07** [watson-developer-cloud/go-sdk#59]
**Overview**
_What is the issue? Be concise and clear._

When invoking the `ListFeedback` method for Compare Comply, the response is deserialized incorrectly and this produces an error. This is either a bug in the SDK or a flaw in [the example in the API ref](https://cloud.ibm.com/apidocs/compare-comply/compare-comply?code=go#list-the-feedback-in-a-document).

**Expected behavior**
_What did you expect to happen?_
I expected the results to be printed to the screen as JSON.

**Actual behavior**
_What actually happened?_
I received the following error:
```
panic: An error occurred while unmarshalling the response body: 'parsing time "2019-04-02T14:11:48.938+0000": extra text: +0000'
```
 coming from this line: `panic(responseErr)`

**How to reproduce**
_Help us to reproduce what you experienced. Include your code snippets (without credentials)_
Build and run this code as is:
```go
package main

import (
  "encoding/json"
  "fmt"
  "github.com/IBM/go-sdk-core/core"
  "github.com/watson-developer-cloud/go-sdk/comparecomplyv1"
)

func main() {
  authenticator := &core.IamAuthenticator{
    ApiKey:     "{apikey}",
  }

  options := &comparecomplyv1.CompareComplyV1Options{
    Version: "2018-10-15",
    Authenticator: authenticator,
  }

  compareComply, compareComplyErr := comparecomplyv1.NewCompareComplyV1(options)

  if compareComplyErr != nil {
    panic(compareComplyErr)
  }

  compareComply.SetServiceURL("{url}")

  result, _, responseErr := compareComply.ListFeedback(
    &comparecomplyv1.ListFeedbackOptions{},
  )

  if responseErr != nil {
    panic(responseErr)
  }
  b, _ := json.MarshalIndent(result, "", "  ")
  fmt.Println(string(b))
}
```
**SDK Version**
_Please provide the SDK version here._
`1.0.0`

Specifically, using local clone at comming `ab836657457716599066956900b6c52d0e45c970`

**Additional information:**
- OS: _for example, iOS_
iOS
- Which version of `Go` are you using?
1.12.6

**Comment by ehdsouza** [comment]
This looks like a service issue. Created a issue https://github.ibm.com/Watson-Discovery/compare-and-comply/issues/12182

**Comment by ehdsouza** [comment]
This has been fixed in production
