### ISSUE TITLE
speechtotextv1 is panicing if the websocket handhake fails

### ISSUE THREAD

**Issue by jasonhancock** [watson-developer-cloud/go-sdk#66]
**Overview**
_What is the issue? Be concise and clear._

When a websocket connection cannot be established with the speechtotextv1 service, a panic happens. Specifically, when https://github.com/watson-developer-cloud/go-sdk/blob/master/speechtotextv1/websocket_listener.go#L128 throws a "websocket: bad handshake" error, a panic will result

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x91f5b7]

goroutine 61 [running]:
github.com/gorilla/websocket.(*Conn).WriteMessage(0x0, 0x1, 0xc00060ab60, 0xd8, 0xe0, 0x0, 0x0)
	/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:753 +0x37
github.com/watson-developer-cloud/go-sdk/speechtotextv1.sendStartMessage(0x0, 0xc0001740f0, 0xc0001a3ab0)
	/go/pkg/mod/github.com/watson-developer-cloud/go-sdk@v1.0.0/speechtotextv1/websocket_listener.go:81 +0x8b
github.com/watson-developer-cloud/go-sdk/speechtotextv1.RecognizeListener.OnOpen(0xc000030620, 0xe45320, 0xc0003220c0, 0xc0001740f0, 0x0)
	/go/pkg/mod/github.com/watson-developer-cloud/go-sdk@v1.0.0/speechtotextv1/websocket_listener.go:25 +0x53
github.com/watson-developer-cloud/go-sdk/speechtotextv1.(*SpeechToTextV1).NewRecognizeListener(0xc000122028, 0xe45320, 0xc0003220c0, 0xc0001740f0, 0xc0001d6e40, 0x32, 0xc00011dc60, 0xc00025a240)
	/go/pkg/mod/github.com/watson-developer-cloud/go-sdk@v1.0.0/speechtotextv1/websocket_listener.go:128 +0x20b
github.com/watson-developer-cloud/go-sdk/speechtotextv1.(*SpeechToTextV1).RecognizeUsingWebsocket(0xc000122028, 0xc0001740f0, 0xe45320, 0xc0003220c0)
	/go/pkg/mod/github.com/watson-developer-cloud/go-sdk@v1.0.0/speechtotextv1/speech_to_text_v1_adapter.go:138 +0x3db
github.com/graymeta/mf2/extractors/speechwatson.processFile(0xe3c220, 0xc000122028, 0xc0005fc870, 0x29, 0x0, 0x2ada1d9c0, 0xc67c86, 0x14, 0x0, 0x0, ...)
```

**Expected behavior**
_What did you expect to happen?_

For a panic not to occur

**Actual behavior**
Paniced

**SDK Version**
Tested on both github.com/watson-developer-cloud/go-sdk v1.0.0 and github.com/watson-developer-cloud/go-sdk v1.2.0

**Additional information:**
- OS: _for example, iOS_
- Which version of `Go` are you using?

OS: Centos 7
```
# go version
go version go1.13.6 linux/amd64
```

**Additional context**
_Add any other details about the problem._

It really feels like maybe the `RecognizeUsingWebsocket` should be capable of returning an error if the websocket connection can't be opened. If you don't want to change the interface, then the rest of the package at least needs to be aware that the websocket connection could be nil and protect against that.

**Comment by ehdsouza** [comment]
@jasonhancock thanks reporting this.

Yes, agree that this panic should be gracefully handled. Looking into the code, looks like we should return after an error is encountered: https://github.com/watson-developer-cloud/go-sdk/blob/master/speechtotextv1/websocket_listener.go#L130

Do you want to contribute to this fix?
