### ISSUE TITLE
Can not run the example code: An error occurred while processing the operation response.

### ISSUE THREAD

**Issue by tjoskar** [watson-developer-cloud/go-sdk#82]
**Overview**
> I'm quite new to Go so it might work as intended. 

When I am running the [speech to text](https://github.com/watson-developer-cloud/go-sdk/blob/master/examples/speechtotextv1/speech_to_text_v1.go) example I'm getting the error: `panic: An error occurred while processing the operation response.`. However, if I just run the WebSocket part it works like a charm.

**Expected behavior**
I expect to get back recognized audio.

**Actual behavior**
I'm getting the error: `An error occurred while processing the operation response`.

**How to reproduce**
This is how I did it:

```bash
curl https://raw.githubusercontent.com/watson-developer-cloud/go-sdk/master/examples/speechtotextv1/speech_to_text_v1.go -o speech_to_text_v1.go
curl https://raw.githubusercontent.com/watson-developer-cloud/go-sdk/master/resources/audio_example.mp3 -o audio_example.mp3
```

I then made the following changes:
```diff
diff --git a/speech_to_text_v1.go b/speech_to_text_v1.go
index 576f3bf..5607c2d 100644
--- a/speech_to_text_v1.go
+++ b/speech_to_text_v1.go
@@ -12,11 +12,11 @@ import (
 func main() {
        // Instantiate the Watson Speech To Text service
        authenticator := &core.IamAuthenticator{
-               ApiKey: os.Getenv("YOUR API KEY"),
+               ApiKey: "<my api key>",
        }
        service, serviceErr := speechtotextv1.
                NewSpeechToTextV1(&speechtotextv1.SpeechToTextV1Options{
-                       URL:           "YOUR SERVICE URL",
+                       URL:           "<my service url>",
                        Authenticator: authenticator,
                })

@@ -30,7 +30,7 @@ func main() {
        pwd, _ := os.Getwd()

        // Open file with mp3 to recognize
-       audio, audioErr := os.Open(pwd + "/../../resources/audio_example.mp3")
+       audio, audioErr := os.Open(pwd + "/audio_example.mp3")
        if audioErr != nil {
                panic(audioErr)
        }
@@ -54,7 +54,7 @@ func main() {
        }

        // Example using websockets!
-       audio, _ = os.Open(pwd + "/../../resources/audio_example.mp3")
+       audio, _ = os.Open(pwd + "/audio_example.mp3")

        // callbook can have `OnOpen`, `onData`, `OnClose` and `onError` functions
        callback := myCallBack{}
```

and then build and run:

```
$ go get github.com/IBM/go-sdk-core/core
$ go get github.com/watson-developer-cloud/go-sdk/speechtotextv1
$ go build speech_to_text_v1.go
$ ./speech_to_text_v1
panic: An error occurred while processing the operation response.

goroutine 1 [running]:
main.main()
	speech_to_text_v1.go:48 +0x5bc
```

However, if I just run the web socket example, it works fine:
```diff
diff --git a/speech_to_text_v1.go b/speech_to_text_v1.go
index 576f3bf..2df828e 100644
--- a/speech_to_text_v1.go
+++ b/speech_to_text_v1.go
@@ -29,32 +29,8 @@ func main() {

        pwd, _ := os.Getwd()

-       // Open file with mp3 to recognize
-       audio, audioErr := os.Open(pwd + "/../../resources/audio_example.mp3")
-       if audioErr != nil {
-               panic(audioErr)
-       }
-
-       // Create a new RecognizeOptions for ContentType "audio/mp3"
-       recognizeOptions := service.
-               NewRecognizeOptions(audio).
-               SetContentType("audio/mp3")
-
-       // Call the speechToText Recognize method
-       recognizeResult, _, responseErr := service.Recognize(recognizeOptions)
-
-       // Check successful call
-       if responseErr != nil {
-               panic(responseErr)
-       }
-
-       // Check successful casting
-       if recognizeResult != nil {
-               core.PrettyPrint(recognizeResult, "Recognize")
-       }
-
        // Example using websockets!
```

Do I miss something?

**Additional information:**
- OS: macOS Catalina
- Go: go version go1.14.3 darwin/amd64

**Comment by victorshinya** [comment]
Good point! Right now, I've been working on a new project with Go, and I've got the same error with Watson Assistant (same error message). I think this is SDK related because, when you check the Result object inside the Response object, from any request to Watson, I can see the right response object.

Looking for some advice or updates from Go SDK.

**Comment by germanattanasio** [comment]
Hi @tjoskar let me see if I can find someone to look at this. Sorry for the delay.

btw, feel free to submit a PR if you think you fixed the example

**Comment by tjoskar** [comment]
No worries. 

If I checkout this repo and run the `speech_to_text_v1.go` file it works fine but if I copy the file to any other path on my disk and compiles it an run the program I get the error "An error occurred while processing the operation response" so I guess it is some kind of linking issue. I'm quite new to Go so I'm not sure where to start. 

This is however not a showstopper for me, I'm doing raw http calls (in rust) for the time being.
